import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { ContextProvider } from "@/context/AppContext";
import { ResponsiveSideBar } from "@/components/ResponsiveSideBar/ReponsiveSideBar";
import { MainContent } from "@/components/MainContent/MainContent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} ${"layout"}`}>
				<ContextProvider>
					<ResponsiveSideBar />
					<MainContent className="mainContent">{children}</MainContent>
				</ContextProvider>
			</body>
		</html>
	);
}
